"""initial migration

Revision ID: e50eb1f8f257
Revises: 
Create Date: 2025-04-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50eb1f8f257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=True),
        sa.Column('gcs_uri', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=True),
        sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processstatus'), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_data',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('chart_id', postgresql.UUID(), nullable=False),
        sa.Column('item_name', sa.String(), nullable=False),
        sa.Column('item_value', sa.Text(), nullable=True),
        sa.Column('extracted_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_data_chart_id'), 'extracted_data', ['chart_id'], unique=False)
    op.create_index(op.f('ix_extracted_data_id'), 'extracted_data', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_data_item_name'), 'extracted_data', ['item_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_data_item_name'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_id'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_chart_id'), table_name='extracted_data')
    op.drop_table('extracted_data')
    op.drop_table('charts')
    op.execute('DROP TYPE processstatus')
    # ### end Alembic commands ### 