"""update_processstatus_enum

Revision ID: a96815d49633
Revises: e50eb1f8f257
Create Date: 2025-04-25 06:38:37.922902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a96815d49633'
down_revision: Union[str, None] = 'e50eb1f8f257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_data_id', table_name='extracted_data')
    
    # PostgreSQLのenumタイプを更新
    # 一時的にstatusカラムをテキスト型に変更
    op.execute('ALTER TABLE charts ALTER COLUMN status TYPE TEXT')
    
    # 既存のenumタイプを削除
    op.execute('DROP TYPE processstatus')
    
    # 新しいenumタイプを作成
    op.execute("CREATE TYPE processstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")
    
    # statusカラムを新しいenumタイプに戻す
    op.execute('ALTER TABLE charts ALTER COLUMN status TYPE processstatus USING status::processstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_extracted_data_id', 'extracted_data', ['id'], unique=False)
    
    # 元に戻す場合
    op.execute('ALTER TABLE charts ALTER COLUMN status TYPE TEXT')
    op.execute('DROP TYPE processstatus')
    op.execute("CREATE TYPE processstatus AS ENUM ('pending', 'processing', 'completed', 'failed')")
    op.execute('ALTER TABLE charts ALTER COLUMN status TYPE processstatus USING status::processstatus')
    # ### end Alembic commands ### 