"""add_dual_similarity_thresholds

Revision ID: 8e853c138c45
Revises: bf78f09c4326
Create Date: 2025-06-23 11:20:27.694657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e853c138c45'
down_revision: Union[str, None] = 'bf78f09c4326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_template_items', sa.Column('text_similarity_threshold', sa.Float(), nullable=True))
    op.add_column('extraction_template_items', sa.Column('vector_similarity_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_template_items', 'vector_similarity_threshold')
    op.drop_column('extraction_template_items', 'text_similarity_threshold')
    # ### end Alembic commands ### 